name: Docker Image CI/CD

on:
  repository_dispatch:
    types: [sync_triggered]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/pop  # Ensure 'pop' repository exists on Docker Hub
        tags: |
          type=sha,format=short
          type=ref,event=branch
          type=edge,branch=master # Add an 'edge' tag for convenience
          
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  # Use a Docker Hub Personal Access Token
 
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile_amd64 # Use standard Dockerfile name if possible, otherwise ensure path is correct
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
